# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-18 08:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='file_information',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=526, verbose_name='文件名称')),
                ('file_info', models.TextField(verbose_name='文件备注')),
                ('file_create_time', models.DateTimeField(auto_now_add=True, verbose_name='文件创建时间')),
                ('file_change_time', models.DateTimeField(auto_now=True, verbose_name='文件修改时间')),
                ('file', models.FileField(upload_to='static/work/doc/', verbose_name='文件')),
                ('file_status', models.IntegerField(default=1, verbose_name='当前状态')),
                ('word_path', models.CharField(default='', max_length=256, verbose_name='导出word文件')),
                ('fanyi_zl', models.IntegerField(default=0, verbose_name='翻译种类')),
                ('yuan', models.IntegerField(default=0, verbose_name='源文语言种类')),
                ('mubiao', models.IntegerField(default=0, verbose_name='目标语言种类')),
                ('file_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='yiwen',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('yiwen', models.TextField(verbose_name='译文句子')),
                ('yiwen_change', models.TextField(default=' ', verbose_name='译文修改句子')),
                ('yiwen_style', models.CharField(default='', max_length=256, verbose_name='译文标题样式')),
                ('style_value', models.CharField(default='', max_length=255, verbose_name='样式的值')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work.file_information')),
            ],
        ),
        migrations.CreateModel(
            name='yuanwen',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('yuanwen', models.TextField(verbose_name='原文句子')),
                ('yuanwen_change', models.TextField(default='', verbose_name='原文修改句子')),
                ('yuanwen_style', models.CharField(default='', max_length=256, verbose_name='原文标题样式')),
                ('style_value', models.CharField(default='', max_length=255, verbose_name='样式的值')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work.file_information')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='yiwen',
            name='gl',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='work.yuanwen'),
        ),
        migrations.AddField(
            model_name='yiwen',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
