# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-18 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_yiwen_yiwen_wait_over'),
    ]

    operations = [
        migrations.AddField(
            model_name='file_information',
            name='all_num',
            field=models.IntegerField(default=0, verbose_name='文章总字数'),
        ),
        migrations.AddField(
            model_name='file_information',
            name='all_para',
            field=models.IntegerField(default=0, verbose_name='文章总段数'),
        ),
    ]
