# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-19 02:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0003_auto_20190118_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='file_information',
            name='numing',
            field=models.IntegerField(default=0, verbose_name='已修改的字数'),
        ),
        migrations.AddField(
            model_name='file_information',
            name='paraing',
            field=models.IntegerField(default=0, verbose_name='已修改段数'),
        ),
    ]
