# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-19 02:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0004_auto_20190119_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='file_information',
            name='jindu',
            field=models.IntegerField(default=0, verbose_name='当前的进度'),
        ),
    ]
