# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-23 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0007_auto_20190119_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='file_information',
            name='over_time',
            field=models.CharField(default='', max_length=255, verbose_name='截至时间'),
        ),
    ]
